---
title: "PSetSkills6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(lubridate)
library(base)
library(tidyverse)

```

1.1
```{r}
f1 <-function(x) {
  if (length(x)<3){
    "error"
  } else
  paste0(x[1],",",x[2]," and ",x[3])
}

f1(c("a","b","c"))

```
1.2
```{r}

now()




start = as.Date("1948-12-07")
end = as.Date(now())
end

floor(as.numeric(difftime(end, start, unit="weeks")) / 52.25)


f2 <-function(start) {
  end=as.Date(now())
  floor(as.numeric(difftime(end, start, unit="weeks")) / 52.25)
}

my_birthday=("1996-04-09")

f2(my_birthday)

```

1.3.a


}
```{r}

variance <- function(x, na.rm = TRUE) {
  n <- length(x)
  m <- mean(x, na.rm = TRUE)
  err2 <- (x - m)^2
  sum(err2) / (n - 1)
  
}


x=c(1,2,3,4)

variance(x)
```
1.3.b


```{r}

skewness <- function(x, na.rm = FALSE) {
  n <- length(x)
  m <- mean(x, na.rm = na.rm)
  v <- var(x, na.rm = na.rm)
  (sum((x - m) ^ 3) / (n - 2)) / v ^ (3 / 2)
}


x=c(1,2,3,4,8)

skewness(x)

```

1.3.c



```{r}

stats_summary <- function(df){
  df_1 <- df %>% 
    summarise_if(is.numeric, mean, na.rm = TRUE) %>% 
    as.data.frame( row.name = "mean")
  
  
  df_2 <-df %>%
    summarise_if(is.numeric, variance, na.rm = TRUE) %>% 
    as.data.frame( row.name = "")


  df_3 <-df %>%
    summarise_if(is.numeric, skewness, na.rm = TRUE) %>% 
    as.data.frame( row.name = "skewness")

  df_4 <-rbind(df_1,df_2,df_3)
  cbind(statistic=c("mean","variance","skewness"),df_4)
}



view(stats_summary(diamonds))
             

```


1.4 


```{r}
 check_first_letter_of_string <- function(string, prefix){
str_sub(string, 1, nchar(prefix)) == prefix
}

check_first_letter_of_string("-15894329847", "-")

```


```{r}

drop_last_element <- function(x){
if (length(x) <= 1)return(NULL)
x[-length(x)]
}


drop_last_element(c("fgaæ","ljl","hggf"))




```
1.5

```{r}
greet <- function(time = lubridate::now()) {
  hr <- lubridate::hour(time)
  if (hr < 12) {
    print("good morning")
  } else if (hr < 17) {
    print("good afternoon")
  } else {
    print("good evening")
  }
}
  
  greet(ymd_h("2021-05-25:19"))
  
  greet( ymd_h("2021-05-25:14"))
  
  greet( ymd_h("2021-05-25:11"))
  
  greet( ymd_h("2021-05-25:01"))
  
  greet()
```


2.1.a

```{r}
calculate_mean <- vector("double", ncol(mtcars))
names(calculate_mean) <- names(mtcars)
for (i in names(mtcars)) {
  calculate_mean[i] <- mean(mtcars[[i]])
  
  
}

calculate_mean
```

2.1.b

```{r}
data("mpg")
mpg_uniq <- vector("double", ncol(mpg))
names(mpg_uniq) <- names(mpg)
for (i in names(mpg)) {
  mpg_uniq[i] <- n_distinct(mpg[[i]])
}


mpg_uniq
```
2.1.c

```{r}
n <- 10
# values of the mean
lambda_param <- c(1, 3, 10,30, 100)
poissons <- vector("list", length(lambda_param))
for (i in seq_along(poissons)) {
  poissons[[i]] <- rpois(n, lambda = lambda_param[i])
}

poissons
```
2.2 Combining csv files

```{r}

files <- dir("c:/users/lenovo/downloads/", pattern = "\\.csv$", full.names = TRUE)
files
#> [1] "data//file1.csv" "data//file2.csv" "data//file3.csv"

df_list <- vector("list", length(files))

for (i in seq_along(files)) {
  df_list[[i]] <- read_csv(files[[i]])
}

df_list

combined_csv_files<-(bind_rows(df_list))

combined_csv_files
```
2.3


